/**
 * Auto-generated by the /test skill. Re-running /test refreshes this file.
 * Do not hand-edit — edits will be overwritten. Use docs/testing/test-strategy.md
 * for human-owned content, and edit sub-page routes below their
 * `USER EDITS BELOW` marker for custom UI.
 */

export type Severity = "blocking" | "recommended" | "info";

export interface AreaGap {
  title: string;
  severity: Severity;
}

export interface AreaCoverage {
  score: number; // 0-5
  tests: Record<string, number>;
  findings: string[];
  gaps: AreaGap[];
  summary: string;
}

export interface CoverageSnapshot {
  generatedAt: string;
  summary: {
    overallScore: number;
    blocking: Array<{ id: string; title: string; detail: string; area: string }>;
    recommended: Array<{ id: string; title: string; detail: string; area: string }>;
  };
  areas: Record<string, AreaCoverage>;
}

export const coverage: CoverageSnapshot = {
  generatedAt: "2026-06-06",
  summary: {
    overallScore: 3,
    blocking: [
      {
        id: "e2e-critical",
        title: "No E2E coverage for critical workflows",
        detail:
          "Auth, org invite, Stripe checkout, and newsletter double opt-in have no automated end-to-end test. A regression here ships silently.",
        area: "e2e",
      },
      {
        id: "perf-published",
        title: "Performance scored against last published build",
        detail:
          "Lighthouse runs on the published URL — republish after any frontend change so the score reflects current code.",
        area: "performance",
      },
    ],
    recommended: [
      {
        id: "a11y-axe",
        title: "Add @axe-core/react sweep on marketing routes",
        detail:
          "Smoke tests render every public page but don't assert WCAG. One axe run per route catches the easy 80%.",
        area: "accessibility",
      },
      {
        id: "design-tokens",
        title: "Audit ~10 hardcoded color classes",
        detail:
          "A handful of components still use raw Tailwind color classes instead of semantic tokens. Easy to converge before launch.",
        area: "design",
      },
      {
        id: "analytics-plan",
        title: "Document the event tracking plan",
        detail:
          "No tracking plan exists. Decide which events matter (signup, checkout_started, invite_accepted) and add a single source of truth.",
        area: "analytics",
      },
    ],
  },
  areas: {
    accessibility: {
      score: 3,
      tests: { unit: 1, smoke: 18, axe: 0 },
      findings: [],
      gaps: [
        { title: "No axe-core assertions on rendered pages", severity: "recommended" },
        { title: "Manual keyboard pass on dialogs/menus not recorded", severity: "recommended" },
      ],
      summary:
        "shadcn primitives handle most ARIA correctly and smoke tests prove pages mount. Missing: automated WCAG assertions and a documented keyboard pass.",
    },
    performance: {
      score: 3,
      tests: { lighthouse: 1, profiler: 0 },
      findings: [],
      gaps: [
        { title: "No bundle-size budget recorded", severity: "recommended" },
        { title: "LCP not profiled per critical route", severity: "recommended" },
        { title: "Published Lighthouse stale until next deploy", severity: "blocking" },
      ],
      summary:
        "Source uses display=swap fonts and prioritizes the hero. Republish to refresh Lighthouse, then add a bundle budget.",
    },
    seo: {
      score: 5,
      tests: { scanner: 1 },
      findings: [],
      gaps: [],
      summary:
        "Scanner is green: meta per page via PageSeo, sitemap.xml present, robots.txt allows crawlers, Google Search Console verified.",
    },
    security: {
      score: 5,
      tests: { scanner: 1, deno: 4, deps: 1 },
      findings: [],
      gaps: [],
      summary:
        "All four security scanners (agent, connector, supabase, supabase_lov) returned zero findings. Deno tests cover newsletter + support-chat auth/validation. No dependency vulns.",
    },
    design: {
      score: 4,
      tests: { unit: 1, smoke: 18 },
      findings: [],
      gaps: [
        { title: "~10 raw color classes still in components/pages", severity: "recommended" },
        { title: "No multi-viewport visual snapshot", severity: "info" },
      ],
      summary:
        "Design system tokens (background, foreground, primary, muted) cover the bulk of the UI. A handful of stragglers remain.",
    },
    "functional-e2e": {
      score: 1,
      tests: { unit: 4, smoke: 18, e2e: 0 },
      findings: [],
      gaps: [
        { title: "No E2E framework wired up (Playwright/Cypress)", severity: "blocking" },
        { title: "Critical workflows have no happy-path automation", severity: "blocking" },
        { title: "Edge function tests cover only 2/20+ functions", severity: "recommended" },
      ],
      summary:
        "Vitest smoke + data tests are strong. End-to-end is the biggest gap for a public launch — pick one E2E tool and cover at least signup → invite → checkout.",
    },
    analytics: {
      score: 1,
      tests: {},
      findings: [],
      gaps: [
        { title: "No tracking plan / event registry", severity: "recommended" },
        { title: "No consent banner or analytics provider wired", severity: "recommended" },
      ],
      summary:
        "Nothing is tracked today. Decide whether the public launch needs analytics; if yes, pick a provider and ship a tiny tracking plan.",
    },
  },
};
